2024-12-20 09:02:28,680 - Loan Extractor - ERROR - Exception occured in <function measure_time_async.<locals>.inner at 0x7a294da2d1c0> : 'bytes' object has no attribute 'seek' 
Traceback (most recent call last):
  File "/home/jacques/works/RevolutionAI/Core/Libs-python/src/lxf/services/try_safe.py", line 5, in try_safe_execute_async
    result= await func(**kargs)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/jacques/works/RevolutionAI/Core/Libs-python/src/lxf/services/measure_time.py", line 26, in inner
    result = await func(*arg,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacques/works/RevolutionAI/Core/Libs-python/src/lxf/services/pdf.py", line 107, in get_text_and_tables_from_pdf
    with pdfplumber.open(filename) as pdf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfplumber/pdf.py", line 101, in open
    return cls(
           ^^^^
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfplumber/pdf.py", line 47, in __init__
    self.doc = PDFDocument(PDFParser(stream), password=password or "")
                           ^^^^^^^^^^^^^^^^^
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/pdfparser.py", line 46, in __init__
    PSStackParser.__init__(self, fp)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 545, in __init__
    PSBaseParser.__init__(self, fp)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 193, in __init__
    self.seek(0)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 557, in seek
    PSBaseParser.seek(self, pos)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 220, in seek
    self.fp.seek(pos)
    ^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'seek'
2024-12-20 09:05:31,475 - Loan Extractor - ERROR - Exception occured in <function measure_time_async.<locals>.inner at 0x78c8793fd3a0> : 'bytes' object has no attribute 'seek' 
Traceback (most recent call last):
  File "/home/jacques/works/RevolutionAI/Core/Libs-python/src/lxf/services/try_safe.py", line 5, in try_safe_execute_async
    result= await func(**kargs)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/jacques/works/RevolutionAI/Core/Libs-python/src/lxf/services/measure_time.py", line 26, in inner
    result = await func(*arg,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacques/works/RevolutionAI/Core/Libs-python/src/lxf/services/pdf.py", line 107, in get_text_and_tables_from_pdf
    with pdfplumber.open(filename) as pdf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfplumber/pdf.py", line 101, in open
    return cls(
           ^^^^
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfplumber/pdf.py", line 47, in __init__
    self.doc = PDFDocument(PDFParser(stream), password=password or "")
                           ^^^^^^^^^^^^^^^^^
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/pdfparser.py", line 46, in __init__
    PSStackParser.__init__(self, fp)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 545, in __init__
    PSBaseParser.__init__(self, fp)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 193, in __init__
    self.seek(0)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 557, in seek
    PSBaseParser.seek(self, pos)
  File "/home/jacques/.local/share/virtualenvs/src-Q-3AUKoU/lib/python3.12/site-packages/pdfminer/psparser.py", line 220, in seek
    self.fp.seek(pos)
    ^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'seek'
